/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 04:54:09 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      App app0 = new App();
      Long long0 = new Long(2399L);
      String string0 = app0.getId(long0, "2399--ID--(-)");
      assertEquals("2399--ID--(2399--ID--(-))", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.getId((Long) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // id must not be null
         //
         assertThrownBy("App", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      App app0 = new App();
      Long long0 = new Long(2399L);
      String string0 = app0.getId(long0, (String) null);
      assertEquals("2399--ID--(-)", string0);
  }
}
